services:
  frontend:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASEURL=${NEXT_PUBLIC_API_BASEURL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - buffet-pos-network

networks:
  buffet-pos-network:
    driver: bridge